/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ShellProductosRouteImport } from './routes/_shell.productos'
import { Route as ShellVentasRouteImport } from './routes/_shell.ventas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellProductosRoute = ShellProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVentasRoute = ShellVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/productos': typeof ShellProductosRoute
  '/ventas': typeof ShellVentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/productos': typeof ShellProductosRoute
  '/ventas': typeof ShellVentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRoute
  '/_shell/productos': typeof ShellProductosRoute
  '/_shell/ventas': typeof ShellVentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/productos' | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/productos' | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/auth'
    | '/_shell/productos'
    | '/_shell/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/productos': {
      id: '/_shell/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ShellProductosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ventas': {
      id: '/_shell/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof ShellVentasRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellProductosRoute: typeof ShellProductosRoute
  ShellVentasRoute: typeof ShellVentasRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellProductosRoute: ShellProductosRoute,
  ShellVentasRoute: ShellVentasRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
